version: '3.8'

services:
  web:
    # build: . gebruikt deze indien er nog geen image op dockerhub staat
    image: rcelen14789/php-apache:latest
    container_name: php-apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'rcelen'
      MYSQL_PASSWORD: 'root'
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql

volumes:
  db_data:
